name: Playwright Tests inside Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env_name: [qauto, qauto2]
        include:
          - env_name: qauto
            url: https://qauto.forstudy.space
          - env_name: qauto2
            url: https://qauto2.forstudy.space

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for environment
        run: |
          echo "BASE_URL=${{ matrix.url }}" >> .env.${{ matrix.env_name }}
          echo "HTTP_USERNAME=${{ secrets.HTTP_USERNAME }}" >> .env.${{ matrix.env_name }}
          echo "HTTP_PASSWORD=${{ secrets.HTTP_PASSWORD }}" >> .env.${{ matrix.env_name }}

      - name: Run tests inside Playwright Docker Container
        uses: docker://://microsoft.com
        env:
          ENV: ${{ matrix.env_name }}
        with:
          entrypoint: /bin/sh
          args: -c "npm ci && npx playwright test"

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.env_name }}
          path: playwright-report/
          retention-days: 30
